export const ACTION_TYPES = {
    GET_MANUFACTURERS_START:'GET_MANUFACTURERS_START',
    GET_MANUFACTURERS_SUCCESS:'GET_MANUFACTURERS_SUCCESS',
    GET_MANUFACTURERS_FAILURE:'GET_MANUFACTURERS_FAILURE',
    GET_VIEWS_START:'GET_VIEWS_START',
    GET_VIEWS_SUCCESS:'GET_VIEWS_SUCCESS',
    GET_VIEWS_FAILURE:'GET_VIEWS_FAILURE',
    GET_DEVICE_START:'GET_DEVICE_START',
    GET_DEVICE_SUCCESS:'GET_DEVICE_SUCCESS',
    GET_DEVICE_FAILURE:'GET_DEVICE_FAILURE',
    GET_DEVICE_ONE_START:'GET_DEVICE_START',
    GET_DEVICE_ONE_SUCCESS:'GET_DEVICE_SUCCESS',
    GET_DEVICE_ONE_FAILURE:'GET_DEVICE_FAILURE',
}